### ISSUE TITLE
new stations problem

### ISSUE THREAD

**Issue by pelin99** [flathub/io.gitlab.Goodvibes#1]
hello you all, I am able to add station to the list but good vibes is not able to play them. probably, the problem is that the stations i am trying to add are web pages that do not launch their music automatically as they open. with other words, you have to click a play button once you go to regarding website to launch the radio. (for example http://www.standart.fm/) any ideas?

**Comment by elboulangero** [comment]
Hi Pelin99,

what URL do you enter when you create the new station in Goodvibes? If you use http://www.standart.fm, it's not gonna work. This is the URL of the webpage, and Goodvibes can't do anything with it. Instead you need to know the URL of the audio stream.

How do you know about this URL, you might ask? You have several options. One is to look it up in a dictionary of URLs such as http://www.radio-browser.info/gui/#!/search. Unfortunately, it doesn't seem to be listed there.

Other than that, your best bet is to use the developer tools of your web browser, and look at what URLs are queries by your web browser when you play the station. For example, assuming you're using firefox:

- Open the webpage for the radio
- Stop the playback if ever it's started automatically
- Open `Menu > Web Developer > Toggle Tools`
- In the panel developer panel, click on the `Network` tab, to see the network requests as they pass by
- Now, click on the play button of the radio, and look at the requests
- As you can see, there's a bunch of unrelated requests, because the web page is constantly doing requests. Anyway.
- So, when you click play, you can see a request with the name `playlist.m3u`. Right click there, see the full link? https://mn-nl.mncdn.com/kaybedenlerkulubu/live/playlist.m3u8

Try to give this URL to Goodvibes, and see if that works. Answer: no! Why?

So ideally now, you would want to dig a bit deeper. Launch Goodvibes from the console (and I'm actually not sure exactl *how* you can do that if you installed it from Flathub), with debug logs enabled, and try to play this stream.

```
DBG  08:55:40 ../src/ui/gv-stations-tree-view.c: on_tree_view_button_press_event(): Button pressed: 1
DBG  08:55:40 ../src/ui/gv-stations-tree-view.c: on_tree_view_row_activated(): Row activated, delaying...
DBG  08:55:40 ../src/core/gv-engine.c: set_gst_state(): Setting gst state 'NULL'... success
DBG  08:55:40 ../src/core/gv-playlist.c: gv_playlist_download(): Downloading playlist 'https://mn-nl.mncdn.com/kaybedenlerkulubu/live/playlist.m3u8' (user-agent: 'Goodvibes/0.4.2 (GNU/Linux)')
WARN 08:55:41 ../src/core/gv-playlist.c: on_message_completed(): Failed to parse playlist
```

Failed to parse playlist... So now you'd want to download the playlist, see how it looks like, to understand why Goodvibes can't parse it.

```
$ wget -q https://mn-nl.mncdn.com/kaybedenlerkulubu/live/playlist.m3u8 -O -
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-STREAM-INF:BANDWIDTH=134655,CODECS="mp4a.40.34"
chunklist.m3u8?__mn_sid=7208314366047919995
```

Well, this is clearly not supported, Goodvibes can't parse that. I think up to now Goodvibes always expects a playlist to provide a full URL for the radio stream, for example https://direct.fipradio.fr/live/fip-midfi.mp3. But here..

It looks like it's just a relative path, to be added to the URL, so something like https://mn-nl.mncdn.com/kaybedenlerkulubu/live/chunklist.m3u8?__mn_sid=7208314366047919995 should work. Except that I tried, and it doesn't work. I'm not sure.

Try harder and tell me if you're successful ;)

**Comment by pelin99** [comment]
@elboulangero thanks a lot for your effort! :) i just tried this way for other 2 stations and it worked!

**Comment by elboulangero** [comment]
@pelin99 Better late than never.

So a station like https://mn-nl.mncdn.com/kaybedenlerkulubu/live/playlist.m3u8 (mentioned in the converstation above) is in fact a [HLS Stream](https://en.wikipedia.org/wiki/HTTP_Live_Streaming). It has been supported by GStreamer (ie. the audio engine used by Goodvibes) for a while, but it was not supported by Goodvibes itself, my bad, I didn't know about that kind of stream and how to handle it properly.

It is now supported in the latest version of Goodvibes `0.5.2`, for reference: https://gitlab.com/goodvibes/goodvibes/-/issues/111.

This new version should be available in Flathub in a few hours: https://flathub.org/apps/details/io.gitlab.Goodvibes

Cheers

**Comment by pelin99** [comment]
so good!
