### ISSUE TITLE
--without-ui fails

### ISSUE THREAD

**Issue by ventoux84** [flathub/io.gitlab.Goodvibes#20]
Hello,
When i launch in a terminal`
flatpak run io.gitlab.Goodvibes --without-ui`

the return is
```
$ flatpak run io.gitlab.Goodvibes --without-ui
Gtk-Message: 09:39:41.143: Failed to load module "xapp-gtk3-module"
Gtk-Message: 09:39:41.185: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:39:41.185: Failed to load module "canberra-gtk-module"
---- Goodvibes 0.7.4 ----
Hit Ctrl+C to quit...

```
I run archlinux up to date and xapp  2.2.14-1 is installed

**Comment by elboulangero** [comment]
Stupid question, but just to be sure: what happens if you run `flatpak run io.gitlab.Goodvibes`, does it fail as well?

Next thing, please run with the argument `-l trace` and paste the output here. Thanks!

**Comment by ventoux84** [comment]
Now, after the last update, i can launch and use Goodvibes even if there are these messages.

> Stupid question, but just to be sure: what happens if you run `flatpak run io.gitlab.Goodvibes`, does it fail as well? 
>
Yes the same thing.

> Next thing, please run with the argument `-l trace` and paste the output here. Thanks!
>
Here is the log.
[TraceGoodvibes.pdf](https://github.com/flathub/io.gitlab.Goodvibes/files/9493498/TraceGoodvibes.pdf)

**Comment by elboulangero** [comment]
OK, so the messages are just harmless diagnostic messages. Whether they appear or not depend on the host OS. A longer (and quite technical) explanation can be found here: https://github.com/flatpak/flatpak/issues/3521#issuecomment-944338059

For example, I'm running GNOME/Wayland, in Debian unstable, and I don't see those messages. Here's are some details about my system:

```
## I'm running Wayland
$ echo $XDG_SESSION_TYPE
wayland

## libcanberra is installed
$ dpkg -l | grep canberra-gtk
ii  libcanberra-gtk3-0:amd64
ii  libcanberra-gtk3-module:amd64

## some GTK modules are defined in the environment
$ printenv | grep GTK
GTK_MODULES=gail:atk-bridge
```

As you said, when you run `flatpak run io.gitlab.Goodvibes` it works, despite the error messages? If so, then all is good. If you really want to remove the error messages (so that it looks better), then it seems that the way to go is `flatpak run --env=GTK_MODULES="" io.gitlab.Goodvibes`. Does that work?

When you run with `--without-ui`, I guess Goodvibes is functional? I mean, you can control the player with `goodvibes-client` for example?

NB: even with the `--without-ui` option, Goodvibes still loads GTK and initializes it, if I remember correctly. So it's not surprising if you get the same GTK-related error messages, with or without the option `--without-ui`.

**Comment by ventoux84** [comment]
Yes, now it works, despite the error messages.  All is good.
When i created the issue, i could not launch Goodvibes. I thing that the following update resolved the problem.

Thanks for all. Goodvibes is a great player.

**Comment by elboulangero** [comment]
Good to hear, I'm closing the issue then. Thanks for the kind words!
