### ISSUE TITLE
Multimedia keys?

### ISSUE THREAD

**Issue by AxelTerizaki** [flathub/io.gitlab.Goodvibes#23]
Apparently it's not possible to use the multimedia keys of your keyboard to control goodvibes with the flatpak version. Could it be compiled with that feature please?

**Comment by elboulangero** [comment]
It works for me. I use the GNOME desktop environment. What Desktop Environment do you use?

**Comment by AxelTerizaki** [comment]
Hmmm, I tried it under KDE but never under Gnome. In KDE the option is greyed out on the flatpak version while if I pull it from the arch packages, it's not. 

I don't remember if I tried the flatpak version when I was on gnome.

**Comment by elboulangero** [comment]
The greyed out option is a bit misleading, actually... This option is to enable keybinding via a particular library (libkeybinder), but it's more or less a thing of the past. With modern desktops (such as KDE or GNOME), multimedia keys should work out of the box without this option (actually, checking this option would have no effect).

What you need is to make sure that MPRIS2 dbus server is enabled (in the General options of Goodvibes). From that point, KDE should be able to talk to goodvibes via the MPRIS2 interface, and forward multimedia keys.

If it doesn't work, you need to search about more generally about "mpris2 / flatpak / kde". Maybe you need to install an extra package, or something is not configured right on your system.

**Comment by AxelTerizaki** [comment]
Hmmm, the MPRIS2 and D-Bus options are both enabled, but to no avail.

I looked at other media players to test if MPRIS2 was working like Celluloid but while the media keys work while the app is on focus, they don't anymore if I switch to another app.

Not sure where the issue is though then...

**Comment by elboulangero** [comment]
I suppose that when you hit, for example, Play/Pause, KDE forwards the keystroke only to one app. So if you have several media players running, it will pick the app that has focus, makes sense. (Imagine if you have Celluloid, VLC, and Goodvibes, and the 3 of them start paying at the same time, that wouldn't be very useful...)

If you have only one multimedia app started, maybe KDE will forward the keystroke to this app unconditionally, regardless of focus? So if you only have Goodvibes started, does it work?

**Comment by AxelTerizaki** [comment]
Tried that, closed all apps (even non multimedia ones) and tried to use the flatpak'ed goodvibes, but still no go with the multimedia keys, sadly.

**Comment by elboulangero** [comment]
I tried in a VM. I used Debian bookworm, installed KDE. I installed Flatpak, installed Goodvibes via Flatpak. Multimedia shortcuts work for me, out of the box, with zero configuration.

Are you sure that the KDE "Media Player" applet is running, and does it acknowledge Goodvibes? Under the hood, when you hit the key, it's this little applet that gets the keystroke, and then forward it to a multimedia app. I don't know how you can debug this thing, you'd need to check if it receives the keystrokes to start with...

Here's are some screenshots from my side, with the KDE media player applet:

![Screenshot_20230711_123709](https://github.com/flathub/io.gitlab.Goodvibes/assets/1942580/a6aa8841-0c74-47e8-b147-882fc67fd313)
![Screenshot_20230711_123728](https://github.com/flathub/io.gitlab.Goodvibes/assets/1942580/2234f095-099a-43d3-8248-8ab7088b6afb)

You can also try to start goodvibes from console, and check the logs, with: `flatpak run io.gitlab.Goodvibes -l dbg`

**Comment by AxelTerizaki** [comment]
Thank you, you nailed it down : I had disabled the media player applet. :)

I hadn't needed it until now because the non-flatpak version didn't need it for some reason (nor did other players like VLC or deadbeef).

I guess the issue can be closed then, I suppose there's no other way to make the flatpak version recognize the keys without the applet?

**Comment by elboulangero** [comment]
> I hadn't needed it until now because the non-flatpak version didn't need it for some reason (nor did other players like VLC or deadbeef).

Well, if you disable the media player applet, then I suppose the setting in Goodvibes to enable multimedia keys becomes useful. But from within flatpak, I don't think this setting works anyway (that's why it's disabled in the flatpak version).

I suppose other players (VLC, deadbeef) try to grab the multimedia keys by default (maybe there's an option to enable/disable that, like in Goodvibes).

So there's two situations:
1. no media player applet: the first app that is started (say VLC) grabs the keys, so it works. But as long as VLC is running, it has exclusive access to multimedia keys!
2.  media player applet: it's the applet that has exclusive access to multimedia keys, and it forwards it to media players, based on best guess (I suppose, the app that has focus is favored, if there are more than one multimedia app running). For that to works, the app must have MPRIS2 support (most apps do).

The situation 1 is "legacy", that's the old way of doing things.

Nowadays, as long as you use a modern desktop environment, like GNOME or KDE, it's always situation 2. It's the desktop that grabs the multimedia keys (via an applet, as you've seen in KDE), and that's in charge of deciding which app will receive the keystroke. This approach works much better.

> I suppose there's no other way to make the flatpak version recognize the keys without the applet?

I suppose not. I didn't check to be honest. As I said, nowadays it's always situation 2, and situation 1 (where an app grab the keys exclusively) is disappearing, because it's a bad approach, technically speaking.

**Comment by AxelTerizaki** [comment]
Yep, that sounds fair. I had disabled the media applet because I didn't see any need for it.

Testing this on something like XFCE would be interesting perhaps, I don't know if it grabs the media keys too. Gnome has that, if I remember correctly.

**Comment by elboulangero** [comment]
GNOME has it indeed. XFCE as well, and until recently it would start/stop ALL multimedia apps at the same time, cf. https://gitlab.xfce.org/panel-plugins/xfce4-pulseaudio-plugin/-/issues/46

> I didn't see any need for it

You need it to catch the multimedia keys and forward it to the "right" player, now you know :)
